### ISSUE TITLE
Failing proptype check for component rendered by UIView

### ISSUE THREAD

**Issue by johnywith1n** [ui-router/react#104]
I'm getting a proptype check error

```
Warning: Failed prop type: The prop `foobar` is marked as required in `Editor`, but its value is `undefined`.
    in Editor (created by UIView)
    in UIView (created by Viewer)
    in div (created by Viewer)
    in Viewer (created by UIView)
    in UIView (created by Home)
    in div (created by Home)
    in Home (created by UIView)
    in UIView (created by App)
    in div (created by App)
    in div (created by App)
    in UIRouter (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider
```

I am generating that component through a UIView as such:

```
<UIView render={(Component, props) =>
            <Component {...props} foobar={this.state.foobar} />
          } />
```

If I change it to:

```
<UIView render={(Component, props) =><div></div>
            //<Component {...props} foobar={this.state.foobar} />
          } />
```

I still get the error.

It would appear that the UIView is trying to generate the component one without the given properties before using the `render` property to properly generate the component.

**Comment by elboman** [comment]
I'm not sure it's related to how `UIView` renders it, as it's simply a render function callback: https://github.com/ui-router/react/blob/master/src/components/UIView.tsx#L173

`UIView` takes the function passed in the `render` props and calls it with the component declaration (which you defined in the state) and the props it would habve used if it was rendering it itself, as arguments of that function.

So the actual rendering of the component it's done by you inside that function.

Could you provide the code of the component that's rendering the UIView? I'd like to see where `Editor` gets created.

**Comment by eddiemonge** [comment]
As this issue is a bit old, it is being closed. If you feel like the problem reported is still valid, please add a comment saying it is still affecting you. We will reevaluate it and if it is valid we will reopen it.

Thank you for supporting and contributing to the project.
