### ISSUE TITLE
expose injected props from UI-View interface

### ISSUE THREAD

**Issue by Hotell** [ui-router/react#12]
It would be nice if there was a interface for component props definition. Currently there is none and one has to define it by itself.

Proposed Implementation:
```typescript
interface Resolves {
  [key: string]: any,
  $stateParams: StateParams,
  $transition$: Transition,
}
export interface InjectedProps {
  transition?: Transition,
  resolves?: Resolves,
  className?: string,
  style?: Object,
}
```

so I can use it for my ReactClass or Stateless component like this:

```typescript
import * as React from 'react';
import { Component, DOMAttributes } from 'react';
import { InjectedProps } from 'ui-router-react';

interface FooContainerProps extends InjectedProps<any>,DOMAttributes<any> {}
interface FooContainerState {}

class FooContainer extends Component<FooContainerProps,FooContainerState> {
  render(){
    const {transition} = this.props;
    const {what='awesome'} = transition.params();
    return <div>UI Router is {what}!</div>;
  }
}
```

I can do PR if you are ok with that.

thanks

**Comment by Schlesiger** [comment]
I tried 0.4.0 but it appears props are still only passed if there is a className on UIView; otherwise nothing is passed. I'm not using typescript.

**Comment by elboman** [comment]
Hi @Schlesiger,
I'm not sure what you mean, also if it's related to this issue (which was concerning about the absence of type declaration for the inject props).

Would you care to open a new issue to discuss the problem you're facing?
