### ISSUE TITLE
Is there a way of using `<ReactCSSTransitionGroup/>` with the `<UIView/>` to animate transitions?

### ISSUE THREAD

**Issue by uditalias** [ui-router/react#13]
When wrapping the `<UIView/>` with `<ReactCSSTransitionGroup/>` the animation is not taking place, I think its related to the fact that when transitioning between states, the `<UIView/>` is not rerendered, only its children.
Any way to animate transitions?

**Comment by uditalias** [comment]
I created a PR with a solution here
https://github.com/ui-router/react/pull/14

**Comment by elboman** [comment]
I've been thinking about this, and even if I'd like to support `ReactCSSTransitionGroup`, I'm afraid it's not that simple. I'd like to find a solution that might work for other libs such as `react-motion`.

Unfortunately, as you already said, it's the `UIView` in charge of mounting the *state components*, so unless we want to explicitly support every animation/wrapper lib that might be useful for users, we might need to add a new API to customize the rendering done by `UIView`.

Something along the lines of react-router render prop:
```jsx
<UIRouter plugins={[•••]} states={[•••]}>
  <UIView render={(Component, props) =>
    <SomeWrapperYouMightNeed><Component {...props} /></SomeWrapperYouMightNeed>
  } />
</UIRouter>
```
