### ISSUE TITLE
UISref links work incorrectly with <base> and hashLocationPlugin

### ISSUE THREAD

**Issue by bisubus** [ui-router/react#139]
For `<base href="/">` tag and this router setup that is used on `/foo/` page:
```
const rootState = { name: 'root',
	url: '/',
	component: Root
};

const barState = {
	name: 'bar',
	url: '/bar',
	component: Bar
};

<UIRouter plugins={[hashLocationPlugin]} states={[rootState, barState]}>
	<div>
		<UISref to="bar"><a>bar</a></UISref>
		<UIView/>
	</div>
</UIRouter>
```

`bar` link works properly on click (goes to `bar` state and results in `http://localhost:3000/foo/#/bar` location) but the link itself is `#/bar` and works like `http://localhost:3000/#/bar` when opened in new window (because of how anchors work with `<base>`).

Currently UISref uses StateService `href` to generate a link. Since StateService is unaware of `<base>`, it's understandable why it generates an anchor that doesn't work as expected. Also produces a wrong link when using `absolute`:
```
stateService.href('bar', {}), // '#/bar'
stateService.href('bar', {}, { absolute: true }), // 'http://localhost:3000/#/bar'
```

**Comment by elboman** [comment]
I'm not sure how to reproduce this, as I don't understand if you are serving the app under `localhost:3000/foo`. From the `http://localhost:3000/foo/#/bar` url it looks like it.

UI-Router is handling the routing in the only after the `#` portion since you are using the `hashLocationPlugin`.

Could you set up a `Codesandbox` to reproduce the error?

**Comment by elboman** [comment]
I need to experiment a bit and see what's wrong.

Out of curiosity: since you serving from `/foo`, why isn't base `<base href="/foo">`?

**Comment by bisubus** [comment]
AFAIK, the issue is applicable to latest Router version. Does the demo needs to be updated to it?

**Comment by bisubus** [comment]
The issue is still relevant, bot.

**Comment by bisubus** [comment]
The issue is still relevant, bot.

**Comment by bisubus** [comment]
The issue is still relevant, bot.

**Comment by bisubus** [comment]
The issue is still relevant, bot.
