### ISSUE TITLE
Take the Router Challenge

### ISSUE THREAD

**Issue by grahammendick** [ui-router/react#171]
[The Router Challenge](https://github.com/grahammendick/router-challenge) aims to be to Routers what TodoMVC is to MV* frameworks. It offers the same Music Catalog application built in React using different Routers. For it to be successful I need the help of Router writers like you. Will you [take the Router Challenge](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md) and implement the Music Catalog application using UI-Router, please?

**Comment by christopherthielen** [comment]
@grahammendick How did you learn of ui-router for react?

**Comment by grahammendick** [comment]
General googling. It's a port of your angular router, right? You're gonna like my challenge. It's an assault course for routers
