### ISSUE TITLE
UISrefActive doesn't update when lazy states are loaded

### ISSUE THREAD

**Issue by bhollis** [ui-router/react#204]
I have a header that displays a bunch of links wrapped in `UISrefActive`, and each link refers to a state that's lazy loaded under a placeholder path (for example, "parent.**", and each link refers to state "parent.child" that will be lazy loaded).

Unfortunately, all of these links are shown as active. I suspect it's because the "parent.**" state includes all of them and they haven't been informed of the swapped out real states.

**Comment by johnrgit** [comment]
I've run into this same issue. When clicking a link that loads a "lazy" module, then all the routes in that module/parent get marked as "active". if I do a soft reload of the page, keeping the module/parent route, only the active routes is marked active.  ...and for fun, if I move to a different module (lazy loaded), then all the children in that new module now are marked active.
