### ISSUE TITLE
Issue with UISrefActive in 0.4.0

### ISSUE THREAD

**Issue by consultwithmike** [ui-router/react#22]
We are having trouble getting the `UISrefActive` to work in `0.4.0` because it's indicating `class` is not being supplied. We've marked it up the following ways:

    <UISrefActive class={'active'}>
        <UISref to={UrlName}>
            <a>{Name}</a>
        </UISref>
    </UISrefActive>

and...

    <UISrefActive class="active">
        <UISref to={UrlName}>
            <a>{Name}</a>
        </UISref>
    </UISrefActive>

Both of them end up with this error:

    Warning: Failed prop type: The prop `class` is marked as required in `UISrefActive`, but its value is `undefined`.
        in UISrefActive
        in Unknown (created by Unknown)
        in div (created by Unknown)
        in Unknown (created by AppModulesContainer)
        in div (created by AppModulesContainer)
        in div (created by AppModulesContainer)
        in AppModulesContainer (created by Connect(AppModulesContainer))
        in Connect(AppModulesContainer) (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in div (created by Reporting)
        in Reporting
        in UIRouter
        in Provider

What have we done wrong?

**Comment by elboman** [comment]
It looks strange as I don't see any problem with your code but I tried to recreate the issue and couldn't: http://www.webpackbin.com/V1Rt70U8z

Do you have any more info that can be helpful?

Would you mind trying to reproduce the error in a webpackbin/plunker so I can take a deeper look?

**Comment by consultwithmike** [comment]
Sure, I'll get a Webpackbin up today to try and reproduce it. Thanks for the quick response!

**Comment by elboman** [comment]
Any chance you found how to reproduce the problem @consultwithmike ?

**Comment by consultwithmike** [comment]
@elboman sorry about that. I could never get WebpackBin to work. However, we did resolve the problem. We had the architecture setup to where we were building UISRef components with invalid states. Our apologies sir!
