### ISSUE TITLE
router.stateService.go History Push Error

### ISSUE THREAD

**Issue by Schlesiger** [ui-router/react#28]
After upgrading from 0.3.0 to 0.4.0, I am getting the following error message when using router.stateService.go(statename):

```
Failed to execute 'pushState' on 'History': A history state object with URL 'http://sales/' cannot be created in a document with origin 'http://localhost:8090' and URL 'http://localhost:8090/home'.
```

I still transition correctly to the state; but the url doesn't reflect. Navigating manually with the address also works.

**Comment by elboman** [comment]
I cannot recreate it, would you mind creating a plunker so I can take a deeper look?

Also, what browser are you using?

**Comment by Schlesiger** [comment]
I was using Chrome 53+ I believe. I was also bootstrapping the router config.

I am working on a rewritten prototype to demonstrate what I need for [issue 26](https://github.com/ui-router/react/issues/26). I'll share once complete and it should be able to test both issues.

**Comment by Schlesiger** [comment]
So now I have another issue I've found since I promoting to a non-root URL. Using 'ui-router-react-digest' in <base>, ui-router is getting caught in an infinite redirecting loop. You can see it's also leaving a preceeding / after it errors out: https://wallzero.gitlab.io/ui-router-react-digest/

Anyhow, if you clone the project from [here](https://gitlab.com/wallzero/ui-router-react-digest/tree/master) and run via 'npm run build:demo && npm run start:demo:dev' you'll see the  error:
```
Failed to execute 'pushState' on 'History': A history state object with URL 'http://tab2/' cannot be created in a document with origin 'http://localhost:8080' and URL 'http://localhost:8080/tab1'.
``` 

You'll have to manually go to localhost:8080/tab1 to actually see the views render.

**Comment by Schlesiger** [comment]
I'm going to close this issue and open a new ticket in ui-router/core, since it's unlikely an issue with ui-router/react.
