### ISSUE TITLE
UISrefActive throwing error about undefined class

### ISSUE THREAD

**Issue by consultwithmike** [ui-router/react#31]
I have defined a `UISrefActive` component like the following, but it is throwing an error about an `undefined` value for `class`.

    <UISrefActive class="active">
        <UISref to="home">
            <a>
                <span className="glyphicon glyphicon-dashboard" aria-hidden="true"></span> Dashboard
            </a>
        </UISref>
    </UISrefActive>

The error in the `Console` is:

> Warning: Failed prop type: The prop `class` is marked as required in `UISrefActive`, but its value is `undefined`... in UISrefActive

**Comment by elboman** [comment]
Hi,
I cannot find anything wrong with your code. Can you reproduce the error in a plunker/jsbin so I can take a deeper look?

**Comment by consultwithmike** [comment]
I found the culprit. I was using the https://github.com/insin/babel-plugin-react-html-attrs plugin for the JSX transform in Webpack and that was changing `class` to `className` during build.

Won't be using that plugin again!
