### ISSUE TITLE
Double transition error with dynamically loaded state

### ISSUE THREAD

**Issue by szimek** [ui-router/react#333]
Hi,

I've got the following configuration:
```
const router = new UIRouterReact();
router.plugin(servicesPlugin);
router.plugin(pushStateLocationPlugin);
router.stateRegistry.register({
  name: 'home.**',
  url: '/',
  lazyLoad() {
      return import(/* webpackChunkName: "home" */ './states/home.state');
  },
});
router.locationConfig.baseHref(`/en/`);
const { urlService } = router;
urlService.rules.otherwise({ state: 'home' });
```

```
// ./states/home.state.js
import React from 'react';
import HomePage from '../pages/HomePage';

const states = [
  {
    name: 'home',
    url: '/',
    component: () => <HomePage />,
  },
];

export { states };
```
When trying to go do a page like e.g. `/en/non-existing-page/`, I'm getting the following error:
```
Transition Rejection($id: 0 type: 2, message: The transition has been superseded by a different transition, detail: Transition#0( ''{} -> 'home.**'{"remainder":"non-existing-page/"} ))
```

I've added some logging in `onBefore` hook and that's what I'm getting
```
transition $id: 1
transition from: name: "", url: "^"
transition to: name: "home", url: "/"

transition $id: 0
transition from: name: "", url: "^"
transition to: name: "home.**", url: "/{remainder:any}"
```
Any idea why it happens and how to fix it? In the real app I've got more states and load them all dynamically, so switching to non-dynamic states is not really an option.

**Comment by christopherthielen** [comment]
@szimek this issue is over a year old.  Did you find a solution to your issue?

**Comment by christopherthielen** [comment]
For posterity, this is what may have been happening:
When a future state is activated, the router matches a URL such as `/non-existing-page` to the future state.  It begins a transition to the future state, and executes the `lazyLoad` callback.  After the second chunk is loaded, then it removes the future state and registers the states found within the lazy loaded chunk.  Finally, it re-starts a *new transition* to the URL initially matched `/non-existing-page`.  This second transition supersedes the original transition (which is cancelled) and this time the url matches a state from the lazy loaded chunk.

**Comment by GarfieldDeepClone** [comment]
I think I have exactly the problem that Christopher described. Is there a way to solve this?
