### ISSUE TITLE
How to add to UIRouter Transition Service via props

### ISSUE THREAD

**Issue by colourcolour** [ui-router/react#38]
Is it possible with the new API, to add transition service hooks to the UIRouter component via props (like plugins, state, config) or do I need to bootstrap manually?

**Comment by lukaszgrolik** [comment]
Maybe that's what you're looking for:

```js
const config = router => {
  router.transitionService.onEnter({}, (trans, state) => {
    // ...
  });
};

<UIRouter plugins={plugins} states={states} config={config}>
  <UIView />
</UIRouter>
```
