### ISSUE TITLE
[typescript] How to import Transition model?

### ISSUE THREAD

**Issue by lukaszgrolik** [ui-router/react#41]
Is there a way of using `Transition` model to define a type in Typescript code? Would be nice if something like this was possible:

```ts
import {Transition} from 'ui-router-react'

// ...

// resolve object in state definition
{
  token: 'someToken',
  resolveFn: async (transition: Transition) => {
    // ...       
  },
  deps: ['$transition$']
 }
```

**Comment by Kukkimonsuta** [comment]
`import { Transition } from 'ui-router-core';`

**Comment by elboman** [comment]
With `0.5.0` the lib is going to export everything the core exports, so you're going to be able to import `Transition` from the react lib, as the core is a dependency and shouldn't be used directly.
