### ISSUE TITLE
babel upgrade

### ISSUE THREAD

**Issue by miladvafaeifard** [ui-router/react#481]
consider to upgrade babel version to 7, the old version causes a problem of having dispatch undefined while using redux and react-redux.

i would be happy to help fix this issue if give me a clear point where i can go and dive into a particular area of the problem.

many thanks.

**Comment by miladvafaeifard** [comment]
gently poked @christopherthielen  ? 😃 pretty please help 🆘

**Comment by christopherthielen** [comment]
hi @miladvafaeifard 

I'm confused... I don't think babel is a dependency except for jest-babel which is only used for tests.  We transpile using typescript.  Can you clarify your findings?
