### ISSUE TITLE
Animating transitions

### ISSUE THREAD

**Issue by kaumac** [ui-router/react#50]
What is the best way to animate state transitions? Is this currently supported?

**Comment by elboman** [comment]
The current published version doesn't let you handle animation between states as the component rendering is done under the hood by the `UIView` component.

This commit (https://github.com/ui-router/react/commit/1047b843175b0459682ed03e36315afe4a175a0c) which will be published in `0.5.0` implements the `render` prop in the component to programmatically decide how to manage the state components that get mounted by the router.

**Comment by kaumac** [comment]
Thanks for the reply @elboman. Is the component rendering still an issue on 0.5.0?

I've upgraded to 0.5.0 but when I wrap my components with CSSTransitionGroup the transitions still don't work. Is there something that I need to do in order for this to work?

Thanks again!

**Comment by elboman** [comment]
I finally found some time to create an example for the animations of Transitions using `CSSTransitionGroup`, you can find it here: https://github.com/ui-router/react/tree/master/examples/animating-transitions

Let me know if you have any doubts!

**Comment by kaumac** [comment]
I'll give it a try during the weekend. Thanks for the amazing work @elboman !
