### ISSUE TITLE
Redirect to page

### ISSUE THREAD

**Issue by 17x** [ui-router/react#56]
how to redirect to home page when enter index app .   just like this :
127.0.0.1:8090  to 127.0.0.1:8090/home
when i directly enter 127.0.0.1:8090/home . every thing working good .  
I just read docs ( i'm using "@uirouter/react": "^0.5.0" now ) and can not resolve this problem .

`
// app state
const appState = {
    name: 'app',
    redirectTo: 'app.home',
    //redirectTo: 'home',
    component: App
};

// home state
const homeStates = {
    parent: 'app',
    name: 'home',
    url: '/home',
    component: Home
};
`

thanks !

**Comment by johnrgit** [comment]
with what you've said... the best advice I can offer is: 

`const configRouter = router => {
    router.urlRouter.otherwise("/");
};`

You need to set a default route i.e. "/", or in your case, "/home"

Hope that helps
