### ISSUE TITLE
UIView multiple views?

### ISSUE THREAD

**Issue by dspencerr** [ui-router/react#58]
Thanks so much for the port to ReactJs!  Cannot imagine routing without ui-router.   

I've spent many years using UI-Router with Angular, now I have moved to react, and am using the port.  I know we can make multiple views in angular via <div ui-view='myView1'></div> and then defining views:{ 'myView':{component:myComponent} }.

Wondering how to do this in React?  I went through the docs and examples, and did not see it. Totally could have been me missing it though.  Thanks again!

**Comment by Kukkimonsuta** [comment]
I have not used multiple views yet, but you can see how it may be done here: https://github.com/ui-router/sample-app-react/blob/master/src/mymessages/states.js

**Comment by dspencerr** [comment]
Thanks @Kukkimonsuta.  I had not seen that example app, and it had a lot of good stuff in it.  
    '^.^.$default': {
      //bindings: { pristineContact: "contact" },
      component: EditContact
    }
I believe what you were referring to was this line of code.  It was helpful, and I realized you can target parent UIViews with children ... which is awesome.  The problem still exists, I cannot for the live of me figure out how to make the "named" UIView.   What does that HTML look like?   

<UIView ui-view={'myNamedView'} />

Not really sure how to create the named uiview for the state with multiple views to target.  Thanks for responding though, it was really useful.

**Comment by dspencerr** [comment]
Ok, I am thick.   

<UIView name='bill' />

that worked
