### ISSUE TITLE
@uirouter/react WARNING in ./~/@uirouter/core/lib/vanilla/*.js

### ISSUE THREAD

**Issue by roger-king** [ui-router/react#60]
Hello,

I am trying to implement ui-router into my react/typescript application (bundling with webpack). I am getting warnings during the bundle on missing *.ts files.

For example: 
`WARNING in ./~/@uirouter/core/lib/hooks/ignoredTransition.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/hooks/ignoredTransition.ts': Error: Can't resolve '../../src/hooks/ignoredTransition.ts'`

I check the node_modules and I do not see the ts files in path. Is there something that I am missing?

Thank you.

**Comment by elboman** [comment]
Not sure why you get the warning. Would you be able to provide a small webpackbin/codesandbox to replicate the error?

**Comment by roger-king** [comment]
Sorry for the late response. I can't seem to replicate in webpackbin, but when I download the zip version I get multiple errors. I tried running the `typescript` example from the react repository when i run it I get 

`ERROR in [at-loader] ./components/Nest.tsx:14:24
    TS2339: Property 'props' does not exist on type 'Nest'.

ERROR in [at-loader] ./node_modules/@uirouter/react/lib/components/UIRouter.d.ts:1:1
    TS2688: Cannot find type definition file for 'react'.

ERROR in [at-loader] ./node_modules/@uirouter/react/lib/components/UISref.d.ts:1:1
    TS2688: Cannot find type definition file for 'react'.

ERROR in [at-loader] ./node_modules/@uirouter/react/lib/components/UISrefActive.d.ts:1:1
    TS2688: Cannot find type definition file for 'react'.

ERROR in [at-loader] ./node_modules/@uirouter/react/lib/components/UIView.d.ts:1:1
    TS2688: Cannot find type definition file for 'react'.

ERROR in [at-loader] ./node_modules/@uirouter/react/lib/components/UIView.d.ts:41:145
    TS2503: Cannot find namespace 'JSX'.

ERROR in [at-loader] ./node_modules/@uirouter/react/lib/components/UIView.d.ts:72:15
    TS2503: Cannot find namespace 'JSX'.

ERROR in [at-loader] ./node_modules/@uirouter/react/lib/interface.d.ts:1:1
    TS2688: Cannot find type definition file for 'react'.`

This happens on multiple computers so I know it isnt a local issue

**Comment by roger-king** [comment]
After doing some deep digging. it seems to be an issue with react-hmre

**Comment by elboman** [comment]
Are you using any starter-kit/boilerplate? Do you know how would I reproduce the bug on my machine so I can dig a bit and see if I can do anything about it?

**Comment by roger-king** [comment]
I am. I'm working on my own react-typescript starter seed.

https://github.com/roger-king/reactjs-modern-seed/tree/master

`npm install`
`npm run generate:container`
`npm run dev`

The second command will get you a quick container or page. Can do a Hello world.

**Comment by roger-king** [comment]
Any chance we have any insight on these warning I could be getting?

**Comment by elboman** [comment]
Hey, sorry for the late response.

I tried you repo reverting back to [24a4349](https://github.com/roger-king/reactjs-modern-seed/commit/24a4349d0c9b5ddc18eb49b515a8ebc3513bc5c7) before the switch to `react-router`, but there must be something wrong with the set up as spinning up the app with `yarn run dev` gives me lots of errors from the `at-loader` on compile.

I think the project loads `react` and `react-dom` type definition twice and that's why it complains. Any branch where I can test this out?

**Comment by eddiemonge** [comment]
As this issue is a bit old, it is being closed. If you feel like the problem reported is still valid, please add a comment saying it is still affecting you. We will reevaluate it and if it is valid we will reopen it.

Thank you for supporting and contributing to the project.
