### ISSUE TITLE
404 on react-dom.js on the tutorial pages

### ISSUE THREAD

**Issue by accidentallyc** [ui-router/react#630]
Just letting you know that [https://unpkg.com/react-dom@16.13.1/dist/react-dom.js](https://unpkg.com/react-dom@16.13.1/dist/react-dom.js) is throwing a 404 for the plunkr examples on the tutorial pages 

- [https://ui-router.github.io/react/tutorial/helloworld](https://ui-router.github.io/react/tutorial/helloworld)
- [https://ui-router.github.io/react/tutorial/hellosolarsystem](https://ui-router.github.io/react/tutorial/hellosolarsystem)
- [https://ui-router.github.io/react/tutorial/hellogalaxy](https://ui-router.github.io/react/tutorial/hellogalaxy)

Console Error
```
(SystemJS) XHR error (404) loading https://unpkg.com/react-dom/dist/react-dom.js
	Error: XHR error (404) loading https://unpkg.com/react-dom/dist/react-dom.js
	    at o (https://unpkg.com/systemjs@0.19.47/dist/system.js:4:17461)
	    at XMLHttpRequest.W.i.onreadystatechange (https://unpkg.com/systemjs@0.19.47/dist/system.js:4:18049)
	Error loading https://unpkg.com/react-dom/dist/react-dom.js as "react-dom" from https://run.plnkr.co/preview/ck8apfpa200053b5z68ksle6r/helloworld.js
```

**Comment by christopherthielen** [comment]
thank you for letting us know! I'll migrate those to stackblitz (and I will delete all the old-school talk of systemjs and module loaders)

**Comment by christopherthielen** [comment]
I've migrated all the react tutorials to stackblitz.  Thanks again for reporting!
