### ISSUE TITLE
UISrefActive active state taking into account params

### ISSUE THREAD

**Issue by wilsonsergio2500** [ui-router/react#67]
Hello,
I have the following scenario
```
<UISrefActive class="active" key={index} exact={false} >
                <UISref to={dynamicView} params={{ page, filterType }}>
```
and the class="active" state is taking into account the params, in order to set the class as active.

how can I do so that the class is always active irrespective of the parameters given as a default, so in essence be active as long as the state is in the dynamicView path

In ng, we could have done something like
```
$scope.isActive = function() {  
   return $state.includes('playLotteries');
}
```

**Comment by wilsonsergio2500** [comment]
so so far, I just handled it vanilla

```
import { UISref, UIView, UISrefActive, StateService } from '@uirouter/react';
....
const stateService = this.props.transition.router.stateService as StateService;
const currentRoute = stateService.$current.name;

<UISref to={dynamicView} params={{ bucketId, page, viewtype  }}>
   <li role="presentation" key={index++} className={currentRoute == dynamicView && "active"  }>
                     ...
     </li>
</UISref>
```

I still be interested to learn other ways to handle it with UISrefActive, if any

**Comment by elboman** [comment]
I understand your needs, there currently isn't a way to override the `isActive` logic, but shouldn't be too much work to implement it as function prop in the component.

An example could be:
```jsx
<UISrefActive class="active" key={index} isActive={() =>{}}>
  <UISref to={dynamicView} params={{ page, filterType }}><a>link</a></UISref>
</UISrefActive>
```
And the `isActive` prop would a function called with the `router` instance as argument, so one can implement whatever logic needed and return a `bool`.

Would like to know what @christopherthielen thinks  about it.

**Comment by christopherthielen** [comment]
My gut instinct is that this doesn't belong in UISrefActive.  It seems trivial enough to do it "vanilla" style.

> how can I do so that the class is always active irrespective of the parameters given as a default, so in essence be active as long as the state is in the dynamicView path

I might put the default parameter values on the dynamic state(s), then link to the state without any explicit values.

```
const state = { 
  name: 'dyn1',
  params: { 
   page: 0,
   filterType: { }
  }
}
```
```
                <UISref to={dynamicView}>
```

**Comment by eddiemonge** [comment]
As this issue is a bit old, it is being closed. If you feel like the problem reported is still valid, please add a comment saying it is still affecting you. We will reevaluate it and if it is valid we will reopen it.

Thank you for supporting and contributing to the project.
