### ISSUE TITLE
ui-router doesn't catch nested lazy loaded states

### ISSUE THREAD

**Issue by Hotell** [ui-router/react#7]
When I have state structure like this ( nested + lazily loaded )

``` typescript
// About 
const rootState = {
  name: 'about',
  url: '/about', 
  lazyLoad: () => System.import('./about').then(module=>module.states) 
}

// Contact
const aboutState = {
  name: 'about.contact',
  url: '/contact', 
  lazyLoad: () => System.import('./contact').then(module=>module.states)
}
```

About and nested Contact wont catch, when going directly to `/about/contact`, and transition to nothing, although About chunk loads, but that's it.

Here is the code:
https://github.com/ngParty/React-scaffold/tree/ui-router

Here is the gif:

![ui-react-router-lazy-load-bug](https://cloud.githubusercontent.com/assets/1223799/19832690/15c4f2d6-9e2b-11e6-832e-c67e791cb35a.gif)

**Comment by christopherthielen** [comment]
https://ui-router.github.io/docs/latest/interfaces/state.statedeclaration.html#lazyload

I think that should be:

```js
// About 
const rootState = {
  name: 'about',
  url: '/about', 
  lazyLoad: () => System.import('./about').then(module=>module.states) 
}

// Contact
const aboutState = {
  name: 'about.contact',
  url: '/contact', 
  lazyLoad: () => System.import('./contact').then(module=>module.states)
}
```

**Comment by Hotell** [comment]
Yeah typo, updated

**Comment by Hotell** [comment]
yeah, typo, updated 

https://github.com/ngParty/React-scaffold/blob/ui-router/src/about/About.routing.ts#L10

**Comment by christopherthielen** [comment]
Thank you for the bug report. There is a fix coming in UI router core version 1.0.2

**Comment by Hotell** [comment]
Awesome! 

off topic question, what about ui-router with redux? Is there something planned? I can help with that. I'm currently migrating from RR2 to fantastic UI-Router but the redux thing is only missing piece to perfection.

thanks

**Comment by elboman** [comment]
I'd like to discuss about the redux integration here (#9) to see what you had in mind
