### ISSUE TITLE
Scroll restoration

### ISSUE THREAD

**Issue by SimonChaumet** [ui-router/react#705]
After one hour searching the doc I can't find a solution for scroll restoration in angularjs version neither in react version.

Is there any support that keeps the scroll position for each page ?
If I need to code it myself which events should I register to save the scroll position ?

Thanks for your responses.

**Comment by christopherthielen** [comment]
There isn't built-in scroll restoration in uirouter/react.  If you do spend time to build it, maybe it would be useful as an add-on
