### ISSUE TITLE
<UIRouter /> Incorrect initialization

### ISSUE THREAD

**Issue by cef62** [ui-router/react#74]
Using  version `0.5.4` we encountered an issue using together `states` and `config` props.
In the component constructor the [provided](https://github.com/ui-router/react/blob/0.5.4/src/components/UIRouter.tsx#L69) `config` is executed before registering the `states`.
Inside the `config` function we are registering an `otherwise` rule that triggers before any state is available and therefore the app is redirected to the default fallback we provide.

To solve the issue the execution of `config` and the `states` registration should be inverted.
If this order is intentional could you suggest me where we should register the `otherwise` rule?

I can open a PR if you confirm me that the behaviour is not intentional.

This is a sample of what we are doing: 

```javascript
function configRouter(router) {
     router.urlService.rules.otherwise(() => '/login')
     router.start()
}

class App extends React.Component {
    render() {
        return (
            <UIRouter
                  states={this.props.states}
                  config={this.props.configRouter}
                  plugins={this.props.plugins}
                >
                  <div><UIView /></div>
            </UIRouter>
        )
    }
}
```

Thanks again for the great library and the effort you put in it.

**Comment by elboman** [comment]
Hi, thanks for the issue. The described behaviour is actually intended and has been updated here: https://github.com/ui-router/react/pull/27 

Unfortunately there are things that make more sense to be configured before states registration, and some after.

The solution is to do manual bootstrapping of the router by initialising the router yourself and pass it to the the component via prop once everything needed is set up.

A solution to support this with react API would be to add a secondary post init config prop to run configuration after everything is set up as well, but I'm not sure that makes much sense, as I consider this an advanced setup and the manual bootstrapping is there for these reasons.

**Comment by cef62** [comment]
Thanks very much! Your solution makes sense, I'll refactor to manual bootstrap ui-router initialization.
