### ISSUE TITLE
UISref Component ignores target="_blank" on child anchor tag

### ISSUE THREAD

**Issue by jesse-smith-dev** [ui-router/react#786]
Behaviour: Link opens in current window
Expected behaviour: Link opens in new window

**Comment by christopherthielen** [comment]
Agreed, this should be addressed in the component.

This makes me wonder: how could this even be handled in the `useSref` hook?

**Comment by christopherthielen** [comment]
Copying behavior from uirouter for angularjs, if any `target` attribute is present, or shift/alt/meta/ctrl is held down, the transition isn't started and it falls back to native browser behavior

**Comment by christopherthielen** [comment]
Released in https://github.com/ui-router/react/releases/tag/1.0.6
