### ISSUE TITLE
Event triggering

### ISSUE THREAD

**Issue by jiobots** [ui-router/react#85]
Hi,

I have a question. Is there any event triggered when there is a change in STATE.
If not, how do we achieve the same. Some thing like BROADCAST EVENT which can listened too

**Comment by elboman** [comment]
Do you need a way to trigger arbitrary logic whenever the application state has changed?
If so, you should use hooks, which are registered to be run whenever a transition hits certain criteria: https://ui-router.github.io/react/docs/latest/modules/hooks.html

**Comment by jiobots** [comment]
Thank You!
