### ISSUE TITLE
Mocking UiRouter Classes with Jest

### ISSUE THREAD

**Issue by jennyeg** [ui-router/react#877]
Hi! In our react app we are using UiRouter. When our team has tried to create unit tests, using jest and enzyme, for our components that are involved with the UiRouter we are getting several errors from the UiRouter. I was wondering if you could provide me with some information on how to appropriately mock the UiRouter in a unit test. The error our team is facing looks like the following:

TypeError: Cannot read property 'rules' of undefined

This is occurring in our router file where we are calling router.urlService.rules.initial( {state: "fakeState"} );

How can we mock the urlService class and the UrlRulesAPI implemented by the urlService class that is provided by the UiRouter so that our unit tests will pass successfully? 

Note: we are currently already mocking the uirouter module as follows: 
jest.mock('@uirouter/react');

Thank you for your help!

**Comment by christopherthielen** [comment]
It depends what you're trying to test, but I've had success mocking just the `uirouter.stateService.go` function.

For example: https://github.com/ui-router/react/blob/24a678d90ef95e79b52b8a4e7fa5b0433774eaea/src/components/__tests__/UISref.test.tsx#L68-L80

**Comment by muz3** [comment]
@christopherthielen, thanks. this is helpful.

> It depends what you're trying to test, but I've had success mocking just the `uirouter.stateService.go` function.
> 
> For example:
> 
> https://github.com/ui-router/react/blob/24a678d90ef95e79b52b8a4e7fa5b0433774eaea/src/components/__tests__/UISref.test.tsx#L68-L80
